--------------------------------------------------------
--  파일이 생성됨 - 수요일-7월-28-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ATCH_FILE
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."ATCH_FILE" 
   (	"ATCH_FILE_ID" NUMBER, 
	"CREAT_DT" DATE, 
	"USE_AT" CHAR(1 BYTE), 
	"USER_ID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE"."CREAT_DT" IS '생성일시';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE"."USE_AT" IS '사용여부';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE"."USER_ID" IS '회원ID
';
--------------------------------------------------------
--  DDL for Table ATCH_FILE_DETAIL
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."ATCH_FILE_DETAIL" 
   (	"ATCH_FILE_ID" NUMBER, 
	"FILE_SN" NUMBER, 
	"FILE_STRE_COURS" VARCHAR2(2000 BYTE), 
	"STRE_FILE_NM" VARCHAR2(300 BYTE), 
	"ORIGNL_FILE_NM" VARCHAR2(300 BYTE), 
	"FILE_EXTSN" VARCHAR2(50 BYTE), 
	"FILE_CN" CLOB, 
	"FILE_SIZE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" 
 LOB ("FILE_CN") STORE AS BASICFILE (
  TABLESPACE "TS_202101M" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."FILE_SN" IS '파일순번';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."FILE_STRE_COURS" IS '파일저장경로';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."STRE_FILE_NM" IS '저장파일명';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."ORIGNL_FILE_NM" IS '원본파일명';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."FILE_EXTSN" IS '파일확장자';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."FILE_CN" IS '파일내용';
   COMMENT ON COLUMN "TEAM2_202101M"."ATCH_FILE_DETAIL"."FILE_SIZE" IS '파일크기';
--------------------------------------------------------
--  DDL for Table COMMUNITY_BOARD
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."COMMUNITY_BOARD" 
   (	"CB_NM" NUMBER, 
	"PJ_NM" NUMBER, 
	"USER_ID" VARCHAR2(40 BYTE), 
	"CB_TITLE" VARCHAR2(1000 BYTE), 
	"CB_CONTENT" VARCHAR2(1000 BYTE), 
	"CB_DATE" DATE, 
	"ATCH_FILE_ID" NUMBER DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_BOARD"."CB_NM" IS '커뮤니티게시판 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_BOARD"."PJ_NM" IS '프로젝트 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_BOARD"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_BOARD"."CB_TITLE" IS '커뮤니티게시판 제목';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_BOARD"."CB_CONTENT" IS '커뮤니티게시판 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_BOARD"."CB_DATE" IS '커뮤니티게시판 작성일';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_BOARD"."ATCH_FILE_ID" IS '첨부파일번호';
--------------------------------------------------------
--  DDL for Table COMMUNITY_COMMENT
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."COMMUNITY_COMMENT" 
   (	"CC_NM" NUMBER, 
	"CC_CONTENT" VARCHAR2(1000 BYTE), 
	"CC_DATE" DATE, 
	"CC_TYPE" VARCHAR2(30 BYTE), 
	"CB_NM" NUMBER, 
	"USER_ID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_COMMENT"."CC_NM" IS '리뷰게시판 댓글번호';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_COMMENT"."CC_CONTENT" IS '리뷰게시판 댓글 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_COMMENT"."CC_DATE" IS '리뷰게시판 댓글 등록일';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_COMMENT"."CC_TYPE" IS '비공개여부';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_COMMENT"."CB_NM" IS '커뮤니티게시판 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."COMMUNITY_COMMENT"."USER_ID" IS '회원ID
';
--------------------------------------------------------
--  DDL for Table FAQ_BOARD
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."FAQ_BOARD" 
   (	"FAQ_NM" NUMBER, 
	"FAQ_TITLE" VARCHAR2(1000 BYTE), 
	"FAQ_CONTENT" VARCHAR2(1500 BYTE), 
	"FAQ_DATE" DATE, 
	"USER_ID" VARCHAR2(40 BYTE), 
	"ATCH_FILE_ID" NUMBER DEFAULT NULL, 
	"FAQ_STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."FAQ_BOARD"."FAQ_NM" IS 'FAQ게시판번호';
   COMMENT ON COLUMN "TEAM2_202101M"."FAQ_BOARD"."FAQ_TITLE" IS 'FAQ게시판 제목';
   COMMENT ON COLUMN "TEAM2_202101M"."FAQ_BOARD"."FAQ_CONTENT" IS 'FAQ 게시판 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."FAQ_BOARD"."FAQ_DATE" IS 'FAQ 게시판 작성일';
   COMMENT ON COLUMN "TEAM2_202101M"."FAQ_BOARD"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."FAQ_BOARD"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."FAQ_BOARD"."FAQ_STATE" IS '삭제유무';
--------------------------------------------------------
--  DDL for Table FREE_BOARD
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."FREE_BOARD" 
   (	"FREE_NM" NUMBER, 
	"FREE_TITLE" VARCHAR2(1000 BYTE), 
	"FREE_CONTENT" VARCHAR2(1000 BYTE), 
	"FREE_DATE" DATE, 
	"USER_ID" VARCHAR2(40 BYTE), 
	"ATCH_FILE_ID" NUMBER DEFAULT NULL, 
	"FREE_STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."FREE_BOARD"."FREE_NM" IS '자유게시판 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_BOARD"."FREE_TITLE" IS '자유게시판 제목';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_BOARD"."FREE_CONTENT" IS '자유게시판 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_BOARD"."FREE_DATE" IS '자유게시판 작성일';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_BOARD"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_BOARD"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_BOARD"."FREE_STATE" IS '삭제여부';
--------------------------------------------------------
--  DDL for Table FREE_COMMENT
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."FREE_COMMENT" 
   (	"FC_NM" NUMBER, 
	"FC_CONTENT" VARCHAR2(1000 BYTE), 
	"FC_DATE" DATE, 
	"FC_TYPE" VARCHAR2(30 BYTE), 
	"FREE_NM" NUMBER, 
	"USER_ID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."FREE_COMMENT"."FC_NM" IS '자유게시판 댓글번호';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_COMMENT"."FC_CONTENT" IS '자유게시판 댓글 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_COMMENT"."FC_DATE" IS '자유게시판 댓글 등록일';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_COMMENT"."FC_TYPE" IS '비공개여부';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_COMMENT"."FREE_NM" IS '자유게시판 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."FREE_COMMENT"."USER_ID" IS '회원ID
';
--------------------------------------------------------
--  DDL for Table LIKEY
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."LIKEY" 
   (	"LIKEY_CODE" VARCHAR2(20 BYTE), 
	"LIKEY_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."LIKEY"."LIKEY_CODE" IS '회원 관심사 코드';
   COMMENT ON COLUMN "TEAM2_202101M"."LIKEY"."LIKEY_NAME" IS '관심사명';
--------------------------------------------------------
--  DDL for Table MEMBER2
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."MEMBER2" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Table NOTICE_BOARD
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."NOTICE_BOARD" 
   (	"NOTICE_NM" NUMBER, 
	"NOTICE_TITLE" VARCHAR2(100 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTICE_DATE" DATE, 
	"USER_ID" VARCHAR2(40 BYTE), 
	"ATCH_FILE_ID" NUMBER DEFAULT NULL, 
	"NOTICE_STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_BOARD"."NOTICE_NM" IS '공지사항 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_BOARD"."NOTICE_TITLE" IS '공지사항 게시판 제목';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_BOARD"."NOTICE_CONTENT" IS '공지사항 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_BOARD"."NOTICE_DATE" IS '공지사항 작성일';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_BOARD"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_BOARD"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_BOARD"."NOTICE_STATE" IS '삭제여부';
--------------------------------------------------------
--  DDL for Table NOTICE_COMMENT
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."NOTICE_COMMENT" 
   (	"NC_NM" NUMBER, 
	"NC_CONTENT" VARCHAR2(1000 BYTE), 
	"NC_DATE" DATE, 
	"NC_TYPE" VARCHAR2(30 BYTE), 
	"NOTICE_NM" NUMBER, 
	"USER_ID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_COMMENT"."NC_NM" IS '공지사항 게시판 작성자';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_COMMENT"."NC_CONTENT" IS '공지게시판 댓글 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_COMMENT"."NC_DATE" IS '공지게시판 댓글 등록일';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_COMMENT"."NC_TYPE" IS '비공개여부';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_COMMENT"."NOTICE_NM" IS '공지사항 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."NOTICE_COMMENT"."USER_ID" IS '회원ID
';
--------------------------------------------------------
--  DDL for Table PROJECT
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."PROJECT" 
   (	"PJ_NM" NUMBER, 
	"PJ_TYPE" VARCHAR2(30 BYTE), 
	"PJ_NAME" VARCHAR2(1000 BYTE), 
	"PJ_CONTENT" VARCHAR2(4000 BYTE), 
	"PJ_PRICE_AMOUNT" NUMBER, 
	"PJ_CONDITION" VARCHAR2(20 BYTE), 
	"PJ_DDAY" DATE, 
	"PJ_OPENDAY" DATE, 
	"PJ_REWARD" VARCHAR2(30 BYTE), 
	"USER_ID" VARCHAR2(40 BYTE), 
	"ATCH_FILE_ID" NUMBER DEFAULT -1, 
	"PJ_CATEGORY" VARCHAR2(20 BYTE), 
	"PJ_ACNTBANK" VARCHAR2(20 BYTE), 
	"PJ_ACNTNUM" VARCHAR2(20 BYTE), 
	"PJ_ACNTHOLDER" VARCHAR2(20 BYTE), 
	"PJ_PRICE" NUMBER, 
	"PJ_FAN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_NM" IS '프로젝트 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_TYPE" IS '프로젝트 타입(일반완료|앵콜) ';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_NAME" IS '프로젝트 이름 ';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_CONTENT" IS '프로젝트 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_PRICE_AMOUNT" IS '목표달성금액';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_CONDITION" IS '심사중/편딩중/심사완료';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_DDAY" IS '프로젝트 마감일';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_OPENDAY" IS '프로젝트 공개일시';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_REWARD" IS '프로젝트 리워드 ';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_ACNTBANK" IS '은행';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_ACNTNUM" IS '계좌번호';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_ACNTHOLDER" IS '예금주';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_PRICE" IS '현재 모인 금액';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT"."PJ_FAN" IS '후원자 수';
--------------------------------------------------------
--  DDL for Table PROJECT_OPTION
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."PROJECT_OPTION" 
   (	"PO_NM" NUMBER, 
	"PO_NAME" VARCHAR2(1000 BYTE), 
	"PO_CONTENT" VARCHAR2(1000 BYTE), 
	"PO_ADD_PRICE" NUMBER, 
	"PJ_NM" NUMBER, 
	"ATCH_FILE_ID" NUMBER DEFAULT -1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT_OPTION"."PO_NM" IS '상품옵션번호';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT_OPTION"."PO_NAME" IS '상품옵션명';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT_OPTION"."PO_CONTENT" IS '상품옵션내용';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT_OPTION"."PO_ADD_PRICE" IS '상품옵션금액';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT_OPTION"."PJ_NM" IS '프로젝트 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."PROJECT_OPTION"."ATCH_FILE_ID" IS '첨부파일 번호';
--------------------------------------------------------
--  DDL for Table QNA_BOARD
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."QNA_BOARD" 
   (	"QNA_NM" NUMBER, 
	"QNA_TITLE" VARCHAR2(1000 BYTE), 
	"QNA_CONTENT" VARCHAR2(1000 BYTE), 
	"QNA_DATE" DATE, 
	"USER_ID" VARCHAR2(40 BYTE), 
	"ATCH_FILE_ID" NUMBER DEFAULT NULL, 
	"QNA_STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."QNA_BOARD"."QNA_NM" IS 'QnA 게시판 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_BOARD"."QNA_TITLE" IS 'QnA 게시판 제목';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_BOARD"."QNA_CONTENT" IS 'QnA 게시판 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_BOARD"."QNA_DATE" IS 'QnA 게시판 작성일';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_BOARD"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_BOARD"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_BOARD"."QNA_STATE" IS '삭제여부';
--------------------------------------------------------
--  DDL for Table QNA_COMMENT
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."QNA_COMMENT" 
   (	"QC_NM" NUMBER, 
	"QC_CONTENT" VARCHAR2(1000 BYTE), 
	"QC_DATE" DATE, 
	"QC_TYPE" VARCHAR2(30 BYTE), 
	"QNA_NM" NUMBER, 
	"USER_ID" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."QNA_COMMENT"."QC_NM" IS 'QnA게시판 댓글번호';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_COMMENT"."QC_CONTENT" IS 'QnA게시판 댓글 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_COMMENT"."QC_DATE" IS 'QnA게시판 댓글 등록일';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_COMMENT"."QC_TYPE" IS '비공개여부';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_COMMENT"."QNA_NM" IS 'QnA 게시판 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."QNA_COMMENT"."USER_ID" IS '회원ID
';
--------------------------------------------------------
--  DDL for Table REPORT_BOARD
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."REPORT_BOARD" 
   (	"REPORT_NM" NUMBER, 
	"REPORT_TITLE" VARCHAR2(100 BYTE), 
	"REPORT_CONTENT" VARCHAR2(1000 BYTE), 
	"REPORT_DATE" DATE, 
	"USER_ID" VARCHAR2(40 BYTE), 
	"ATCH_FILE_ID" NUMBER DEFAULT NULL, 
	"REPORT_STATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."REPORT_BOARD"."REPORT_NM" IS 'REPORT게시판 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."REPORT_BOARD"."REPORT_TITLE" IS 'REPORT 게시판 제목';
   COMMENT ON COLUMN "TEAM2_202101M"."REPORT_BOARD"."REPORT_CONTENT" IS 'REPORT 게시판 내용';
   COMMENT ON COLUMN "TEAM2_202101M"."REPORT_BOARD"."REPORT_DATE" IS 'REPORT 게시판 작성일';
   COMMENT ON COLUMN "TEAM2_202101M"."REPORT_BOARD"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."REPORT_BOARD"."ATCH_FILE_ID" IS '첨부파일번호';
   COMMENT ON COLUMN "TEAM2_202101M"."REPORT_BOARD"."REPORT_STATE" IS '삭제유무';
--------------------------------------------------------
--  DDL for Table TB_ORDER
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."TB_ORDER" 
   (	"ORDER_NM" NUMBER, 
	"ORDER_BILL" VARCHAR2(100 BYTE), 
	"ORDER_STATE" VARCHAR2(30 BYTE), 
	"PJ_NM" NUMBER, 
	"USER_ID" VARCHAR2(40 BYTE), 
	"ORDER_TIME" DATE, 
	"ORDER_PRICE" VARCHAR2(30 BYTE), 
	"PO_NAME" VARCHAR2(1000 BYTE), 
	"PJ_NAME" VARCHAR2(100 BYTE), 
	"ATCH_FILE_ID" NUMBER DEFAULT -1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."ORDER_NM" IS '주문번호';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."ORDER_BILL" IS '결제내역';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."ORDER_STATE" IS '주문상태';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."PJ_NM" IS '프로젝트 번호';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."ORDER_TIME" IS '주문시간';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."ORDER_PRICE" IS '주문 금액';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."PO_NAME" IS '옵션명';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."PJ_NAME" IS '프로젝트 이름
';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_ORDER"."ATCH_FILE_ID" IS '첨부파일';
--------------------------------------------------------
--  DDL for Table TB_USER
--------------------------------------------------------

  CREATE TABLE "TEAM2_202101M"."TB_USER" 
   (	"USER_ID" VARCHAR2(40 BYTE), 
	"USER_NAME" VARCHAR2(30 BYTE), 
	"USER_PW" VARCHAR2(40 BYTE), 
	"USER_NICKNAME" VARCHAR2(40 BYTE), 
	"USER_BIR" DATE, 
	"USER_GENDER" VARCHAR2(30 BYTE), 
	"USER_TEL" NUMBER, 
	"USER_EMAIL" VARCHAR2(100 BYTE), 
	"LIKEY_CODE" VARCHAR2(20 BYTE), 
	"USER_ZIP" VARCHAR2(50 BYTE), 
	"USER_ADD1" VARCHAR2(100 BYTE), 
	"USER_ADD2" VARCHAR2(100 BYTE), 
	"USER_MONEY" NUMBER DEFAULT 0, 
	"ADMIN_CK" VARCHAR2(10 BYTE) DEFAULT 'N', 
	"PJ_NM" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;

   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_ID" IS '회원ID
';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_NAME" IS '회원명';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_PW" IS '비밀번호';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_NICKNAME" IS '유저닉네임';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_BIR" IS '생년월일';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_GENDER" IS '회원 성별';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_TEL" IS '전화번호
';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_EMAIL" IS '이메일주소';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."LIKEY_CODE" IS '회원 관심사 코드';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_ZIP" IS '우편번호';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_ADD1" IS '주소1';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_ADD2" IS '상세주소';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."USER_MONEY" IS '회원포인트';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."ADMIN_CK" IS '관리자 유무 확인';
   COMMENT ON COLUMN "TEAM2_202101M"."TB_USER"."PJ_NM" IS '내가 후원한 프로젝트';
--------------------------------------------------------
--  DDL for Index SYS_C00259734
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259734" ON "TEAM2_202101M"."ATCH_FILE" ("ATCH_FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259736
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259736" ON "TEAM2_202101M"."ATCH_FILE_DETAIL" ("ATCH_FILE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259741
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259741" ON "TEAM2_202101M"."COMMUNITY_BOARD" ("CB_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259745
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259745" ON "TEAM2_202101M"."COMMUNITY_COMMENT" ("CC_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259749
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259749" ON "TEAM2_202101M"."FAQ_BOARD" ("FAQ_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259753
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259753" ON "TEAM2_202101M"."FREE_BOARD" ("FREE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259757
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259757" ON "TEAM2_202101M"."FREE_COMMENT" ("FC_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259759
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259759" ON "TEAM2_202101M"."LIKEY" ("LIKEY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."TABLE1_PK" ON "TEAM2_202101M"."MEMBER2" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259763
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259763" ON "TEAM2_202101M"."NOTICE_BOARD" ("NOTICE_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259767
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259767" ON "TEAM2_202101M"."NOTICE_COMMENT" ("NC_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259771
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259771" ON "TEAM2_202101M"."PROJECT" ("PJ_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259774
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259774" ON "TEAM2_202101M"."PROJECT_OPTION" ("PO_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259778
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259778" ON "TEAM2_202101M"."QNA_BOARD" ("QNA_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259782
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259782" ON "TEAM2_202101M"."QNA_COMMENT" ("QC_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259786
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259786" ON "TEAM2_202101M"."REPORT_BOARD" ("REPORT_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259790
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259790" ON "TEAM2_202101M"."TB_ORDER" ("ORDER_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  DDL for Index SYS_C00259800
--------------------------------------------------------

  CREATE UNIQUE INDEX "TEAM2_202101M"."SYS_C00259800" ON "TEAM2_202101M"."TB_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M" ;
--------------------------------------------------------
--  Constraints for Table ATCH_FILE
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."ATCH_FILE" ADD PRIMARY KEY ("ATCH_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."ATCH_FILE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."ATCH_FILE" MODIFY ("ATCH_FILE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ATCH_FILE_DETAIL
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."ATCH_FILE_DETAIL" ADD PRIMARY KEY ("ATCH_FILE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."ATCH_FILE_DETAIL" MODIFY ("ATCH_FILE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUNITY_BOARD
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."COMMUNITY_BOARD" ADD PRIMARY KEY ("CB_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."COMMUNITY_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."COMMUNITY_BOARD" MODIFY ("PJ_NM" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."COMMUNITY_BOARD" MODIFY ("CB_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMUNITY_COMMENT
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."COMMUNITY_COMMENT" ADD PRIMARY KEY ("CC_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."COMMUNITY_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."COMMUNITY_COMMENT" MODIFY ("CB_NM" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."COMMUNITY_COMMENT" MODIFY ("CC_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FAQ_BOARD
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."FAQ_BOARD" ADD PRIMARY KEY ("FAQ_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."FAQ_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."FAQ_BOARD" MODIFY ("FAQ_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE_BOARD
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."FREE_BOARD" ADD PRIMARY KEY ("FREE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."FREE_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."FREE_BOARD" MODIFY ("FREE_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FREE_COMMENT
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."FREE_COMMENT" ADD PRIMARY KEY ("FC_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."FREE_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."FREE_COMMENT" MODIFY ("FREE_NM" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."FREE_COMMENT" MODIFY ("FC_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LIKEY
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."LIKEY" ADD PRIMARY KEY ("LIKEY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."LIKEY" MODIFY ("LIKEY_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER2
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."MEMBER2" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."MEMBER2" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_BOARD
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."NOTICE_BOARD" ADD PRIMARY KEY ("NOTICE_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."NOTICE_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."NOTICE_BOARD" MODIFY ("NOTICE_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_COMMENT
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."NOTICE_COMMENT" ADD PRIMARY KEY ("NC_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."NOTICE_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."NOTICE_COMMENT" MODIFY ("NOTICE_NM" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."NOTICE_COMMENT" MODIFY ("NC_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."PROJECT" ADD PRIMARY KEY ("PJ_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."PROJECT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."PROJECT" MODIFY ("PJ_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROJECT_OPTION
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."PROJECT_OPTION" ADD PRIMARY KEY ("PO_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."PROJECT_OPTION" MODIFY ("PJ_NM" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."PROJECT_OPTION" MODIFY ("PO_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA_BOARD
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."QNA_BOARD" ADD PRIMARY KEY ("QNA_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."QNA_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."QNA_BOARD" MODIFY ("QNA_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA_COMMENT
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."QNA_COMMENT" ADD PRIMARY KEY ("QC_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."QNA_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."QNA_COMMENT" MODIFY ("QNA_NM" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."QNA_COMMENT" MODIFY ("QC_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REPORT_BOARD
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."REPORT_BOARD" ADD PRIMARY KEY ("REPORT_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."REPORT_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."REPORT_BOARD" MODIFY ("REPORT_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ORDER
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."TB_ORDER" ADD PRIMARY KEY ("ORDER_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."TB_ORDER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."TB_ORDER" MODIFY ("PJ_NM" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."TB_ORDER" MODIFY ("ORDER_NM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_USER
--------------------------------------------------------

  ALTER TABLE "TEAM2_202101M"."TB_USER" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_202101M"  ENABLE;
  ALTER TABLE "TEAM2_202101M"."TB_USER" MODIFY ("USER_BIR" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."TB_USER" MODIFY ("USER_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."TB_USER" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."TB_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "TEAM2_202101M"."TB_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
